---
title: "Data_cleaning"
author: "Diwen Si"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Cleaning

## Merging datasets
import library
```{r}
library(haven)
library(Statamarkdown)
library(dplyr)
library(tidyverse)
library(data.table)
library(stargazer)
library(MASS)
library(mfx)
library(sandwich)
library(lmtest)
library(plm)
library(erer)
```


```{r}
filename <- c()
index <- c("a","b", "c", "d","e","f","g","h","i","j","k","l")
for (i in 1:length(index)){
  filename <- c(filename,paste0(index[i],"_indresp.dta"))
  assign(paste0("wave",i), as.data.frame(read_dta(filename[i])))
}
varList <- c("pidp", "sclfsato", "dvage", "fimngrs_dv", "jbstat", "marstat_dv", "health","nchresp", "gor_dv", "hhsize", "pidp", "hidp", "sex", "oprlg", "scend")
```

```{r}
allwaves <- c()
bgn <- c()
allwaves <- paste0("wave",1:12)
allwaves <- mget(allwaves)
for (i in 1:12){
  allwaves <- list(allwaves, paste0("wave",i))
  bgn <- c(bgn,paste0(index,"_"))
}
for (i in 1:12){
  allwaves[i] <- allwaves[i] %>% select(all_of(var_names))
}
```
```{r}
  names(wave1)<- gsub("a_","",names(wave1))
  names(wave2)<- gsub("b_","",names(wave2))
  names(wave3)<- gsub("c_","",names(wave3))
  names(wave4)<- gsub("d_","",names(wave4))
  names(wave5)<- gsub("e_","",names(wave5))
  names(wave6)<- gsub("f_","",names(wave6))
  names(wave7)<- gsub("g_","",names(wave7))
  names(wave8)<- gsub("h_","",names(wave8))
  names(wave9)<- gsub("i_","",names(wave9))
  names(wave10)<- gsub("j_","",names(wave10))
  names(wave11)<- gsub("k_","",names(wave11))
  names(wave12)<- gsub("l_","",names(wave12))
  wave1 <- wave1 %>% select(all_of(varList))
  wave2 <- wave2 %>% select(all_of(varList))
  wave3 <- wave3 %>% select(all_of(varList))
  wave4 <- wave4 %>% select(all_of(varList))
  wave5 <- wave5 %>% select(all_of(varList))
  wave6 <- wave6 %>% select(all_of(varList))
  wave7 <- wave7 %>% select(all_of(varList))
  wave8 <- wave8 %>% select(all_of(varList))
  wave9 <- wave9 %>% select(all_of(varList))
  wave10 <- wave10 %>% select(all_of(varList))
  wave11 <- wave11 %>% select(all_of(varList))
  wave12 <- wave12 %>% select(all_of(varList))
  wave1 <- wave1 %>% mutate(wave = 1)
  wave2 <- wave2 %>% mutate(wave = 2)
  wave3 <- wave3 %>% mutate(wave = 3)
  wave4 <- wave1 %>% mutate(wave = 4)
  wave5 <- wave2 %>% mutate(wave = 5)
  wave6 <- wave3 %>% mutate(wave = 6)
  wave7 <- wave1 %>% mutate(wave = 7)
  wave8 <- wave2 %>% mutate(wave = 8)
  wave9 <- wave3 %>% mutate(wave = 9)
  wave10 <- wave1 %>% mutate(wave = 10)
  wave11 <- wave2 %>% mutate(wave = 11)
  wave12 <- wave3 %>% mutate(wave = 12)
  for (i in 1:12){
   if(!is.null(allwaves[[i]])) {
  allwaves[[i]] <- allwaves[[i]] %>% mutate(wave = i)
   }
}
wave2 <- as.data.frame(wave2)
is.data.frame(wave12)
write_dta(wave1,paste0("wave1.dta"))
for (i in 1:12){
  write_dta(allwaves[[i]],paste0("wave",i,".dta"))
}
```
```{r}
df_names <- paste0("wave", 1:12)

# Loop over the data frame names
for(i in seq_along(df_names)) {
  # Check if the data frame exists and is not NULL
  if(exists(df_names[i]) && !is.null(get(df_names[i]))) {
    df <- get(df_names[i])
    write_dta(df, paste0(df_names[i], ".dta"))
  }
}
```

```{r}

df_names <- paste0("wave", 1:12)


prefixes <- letters[1:12]


for(i in seq_along(df_names)) {
  # Check if the data frame exists and is not NULL
  if(exists(df_names[i]) && !is.null(get(df_names[i]))) {
    df <- get(df_names[i])
    names(df) <- gsub(paste0(prefixes[i], "_"), "", names(df))
    df <- df %>% select(all_of(varList))
    df <- df %>% mutate(wave = i)
    assign(df_names[i], df)
  }
}

```

```{r}
wave1$hidp <- as.numeric(wave1$hidp)
data1 <- rbindlist(mget(paste0("wave",1:12)))
write_dta(data1,"waveall.dta")
summary(data1$wave)
```
## balance the data
```{r}
unbalanced<- read_dta("wave1.dta")
unbalanced <- as.data.frame(unbalanced)
unbalanced<-make.pbalanced(unbalanced, balance.type = "shared.individuals")
```

## generate reference group
```{r}
data1 <- read_dta("waveall.dta")
attach(data1)
summary(dvage)
dvage <- ifelse(dvage <0,NA,dvage)
data1$scend <- ifelse(data1$scend <0,NA,data1$scend)
data1 <- data1 %>%
  group_by(pidp) %>%
  mutate(scend = ifelse(is.na(scend), max(scend,na.rm = TRUE), scend)) %>%
  ungroup()
data1$scend <- ifelse(data1$scend <0,NA,data1$scend)
write_dta(data1,"scend.dta")
```
```{r}
summary(data1$scend)
attach(data1)
data1$edu2 <- cut(data1$scend, breaks = c(-Inf,18.5,Inf), labels = c("low","high"))
data1$edu3 <- cut(data1$scend, breaks = c(-Inf,16.5,18.5,Inf),labels = c("low","mid","high"))
data1$sclfsato <- ifelse(sclfsato<0,NA,sclfsato)
data1$gor_dv <- ifelse(gor_dv < 0, NA,gor_dv)
data1$region4 <- cut(data1$gor_dv, breaks = c(0,9.5,10.5,11.5,12.5),labels = c("England","Wales","Scotland","Northern Ireland"))
data1$age <- data1$dvage^2/50
data1$sex <- as.factor(ifelse(sex<0,NA,sex))
data1$fimngrs_dv <- ifelse(data1$fimngrs_dv<0,NA,data1$fimngrs_dv)

lower_bound <- quantile(data1$fimngrs_dv, 0.01,na.rm = T)
upper_bound <- quantile(data1$fimngrs_dv, 0.99,na.rm = T)

# Subset the data frame

summary(data1$edu3)
summary(data1$sclfsato)

data1 <- na.omit(data1)
data1$group_m1 <- paste(data1$sex, data1$edu3, data1$region4, data1$wave, sep = "_")
data1$group_m1 <- as.factor(as.numeric(as.factor(data1$group_m1)))
data2 <- data1[data1$fimngrs_dv > lower_bound & data1$fimngrs_dv < upper_bound, ]#remove this line for groupm1
write_dta(data2,"groupm2.dta")
```
generate relative rank
```{r}
data1 <- read_dta("groupm1.dta")
for (i in 1:length(data2$dvage)){
  data1$agegrp <- ifelse((data1$dvage < data1$dvage[i]+6.5 & data1$dvage > data1$dvage[i]-3.5),1,0) 
  data1$refg <- data1$agegrp*as.numeric(data1$group_m1)
  data1$refg <- ifelse(data1$refg == data1$refg[i],1,NA)
  data1$inc <- data1$refg*data1$fimngrs_dv
  data1$absrk[i] <- sum(!is.na(data1$inc))-rank(data1$inc)[i]
  data1$grpsize[i] <- sum(!is.na(data1$inc))
}
data1$relrk <- (data1$absrk-1/data1$grpsize-1)
write_dta(data1,"rrankm1.dta")
save(data1, file = "rrankm1.RData")
```
```{r}
data2 <- read_dta("groupm2.dta")
for (i in 1:length(data2$dvage)){
  data2$agegrp <- ifelse((data2$dvage < data2$dvage[i]+6.5 & data2$dvage > data2$dvage[i]-3.5),1,0) 
  data2$refg <- data2$agegrp*as.numeric(data2$group_m1)
  data2$refg <- ifelse(data2$refg == data2$refg[i],1,NA)
  data2$inc <- data2$refg*data2$fimngrs_dv
  data2$absrk[i] <- sum(!is.na(data2$inc))-rank(data2$inc)[i]
  data2$refinc[i]<-mean(data2$inc,na.rm=T)
  data2$grpsize[i] <- sum(!is.na(data2$inc))
}
data2$absrk1 <- data2$grpsize-data2$absrk
round(data2$absrk1, digits = 0)
data2$relrk <- (data2$absrk/data2$grpsize-1)
data2$grpsize1<-ifelse(data2$grpsize>1,data2$grpsize,NA)
data2$relrk1 <- (data2$absrk1-1)/(data2$grpsize1-1)
write_dta(data2,"rrankm2b.dta")
save(data2, file = "rrankm2b.RData")
data1<-data2
```


summary statistics
```{r}

data2 <- read_dta("rrankm2b.dta")
data2 <- subset(data2,select = !(names(data2) %in% c("scend","gor_dv","refg","inc","agegrp","groupm1")))
data2$dvage <- ifelse(data2$dvage <0,NA,data2$dvage)
data2$jbstat <- ifelse(data2$jbstat<0,NA,data2$jbstat)
data2$marstat_dv <- ifelse(data2$marstat_dv<0,NA,data2$marstat_dv)
data2$health <- ifelse(data2$health<0,NA,data2$health)
data2$oprlg <- ifelse(data2$oprlg<0,NA,data2$oprlg)
data2$relrk <- ifelse(is.na(data2$dvage),NA,data2$relrk)
data2$absrk <- ifelse(is.na(data2$dvage),NA,data2$absrk)
data2$grpsize <- ifelse(is.na(data2$dvage),NA,data2$grpsize)
data2$absrk1 <- data2$grpsize-data2$absrk
round(data2$absrk1, digits = 0)
data2$relrk <- (data2$absrk/data2$grpsize-1)
data2$grpsize1<-ifelse(data2$grpsize>1,data2$grpsize,NA)
data2$relrk1 <- (data2$absrk1-1)/(data2$grpsize1-1)
data2$inc <- data2$fimngrs_dv/100
write_dta(data2,"use_reg4b.dta")
stargazer(as.data.frame(data2),type = "latex", title='Summary Statistics',out = "summarys1.txt")
plot(data2$relrk,data2$fimngrs_dv)
```
Estimation


```{r}
load("use_reg.RData")
data2$vcinc <- ifelse(data2$fimngrs_dv<=0,NA,data2$fimngrs_dv)
poolop01 <- polr(as.formula(as.factor(sclfsato) ~ relrk + fimngrs_dv + dvage + age + as.factor(sex) + as.factor(region4) + as.factor(edu2) + hhsize + nchresp + as.factor(health) + as.factor(jbstat) + as.factor(marstat_dv)), data = data2, Hess=TRUE)
poolop02 <- polr(as.formula(as.factor(sclfsato) ~ fimngrs_dv + dvage + age + as.factor(sex) + as.factor(region4) + as.factor(edu2) + hhsize + nchresp + as.factor(health) + as.factor(jbstat) + as.factor(marstat_dv)), data = data2, Hess=TRUE)

stargazer(poolop01,poolop02,out="poolop.txt")
```
```{r}
load("use_reg.RData")
data2$vcinc <- ifelse(data2$fimngrs_dv<=0,NA,data2$fimngrs_dv)

setDT(data2)
data2[fimngrs_dv %between% quantile(fimngrs_dv, c(.01, .99))]
poolop001 <- polr(as.formula(as.factor(sclfsato)~relrk + vcinc + dvage + age + as.factor(sex) + as.factor(region4) + as.factor(edu2) + hhsize + nchresp + as.factor(health) + as.factor(jbstat) + as.factor(marstat_dv)),data = data2, method = "probit",Hess = TRUE, vcinc > 150)
coef(poolop001)
mea <- ocME(w = poolop001); mea

```

```{stata}
oprobit sclfsato relrk fimngrs_dv dvage age i.sex i.region4 i.edu2 hhsize nchresp i.health i.jbstat i.marstat_dv
oprobit sclfsato fimngrs_dv dvage age i.sex i.region4 i.edu2 hhsize nchresp i.health i.jbstat i.marstat_dv
```

average increase in relrk1 for 100GBP increase

```{r}
data11 <- read_dta("use_reg4b.dta")
for (i in 1:length(data11$dvage)){
  data11$fimngrs_dv[i] <- data11$fimngrs_dv[i]+100
  data11$agegrp11 <- ifelse((data11$dvage < data11$dvage[i]+6.5 & data11$dvage > data11$dvage[i]-3.5),1,0) 
  data11$refg11 <- data11$agegrp11*as.numeric(data11$group_m1)
  data11$refg11 <- ifelse(data11$refg11 == data11$refg11[i],1,NA)
  data11$inc11 <- data11$refg11*data11$fimngrs_dv
  data11$absrk11[i] <- sum(!is.na(data11$inc11))-rank(data11$inc11)[i]
  data11$refinc11[i]<-mean(data11$inc11,na.rm=T)
  data11$grpsize11[i] <- sum(!is.na(data11$inc11))
  data11$fimngrs_dv[i] <- data11$fimngrs_dv[i]-100
}
data11$absrk12 <- data11$grpsize11-data11$absrk11
round(data11$absrk12, digits = 0)
data11$grpsize12<-ifelse(data11$grpsize11>1,data11$grpsize11,NA)
data11$relrk12 <- (data11$absrk12-1)/(data11$grpsize12-1)
data11$diff <- data11$relrk12-data11$relrk1
write_dta(data11,"100GBPb.dta")
summary(data11$diff)
```


## Prediction
### generating subjective rank
```{r}
data11 <- read_dta("use_reg4b.dta")
eta <- c(seq(0.95,2,0.05))
sbrknames <- paste0("sbrk",eta*100)
sbrkN <- c()
for (i in 1:length(sbrknames)){
  sbrkN <- 0.5+ ((data11$absrk1-1)-eta[i]*(data11$grpsize1-data11$absrk1))/(2*((data11$absrk1-1)+eta[i]*(data11$grpsize1-data11$absrk1)))
  assign(sbrknames[i],sbrkN)
data11[sbrknames[i]] <- sbrkNs
}
write_dta(data11,"use_predict1b.dta")
```



